### ISSUE TITLE
Do you have test your model in different SNR?

### ISSUE THREAD

**Issue by Ostnie** [Amiralae/modulation-recognition-for-wireless-signals#1]
Hi, I'm learning modulation recognition too,and I test my model in different SNR，and I want to compare with yours so that I can learn something new!

Sadly, my acc is 83% when the SNR is 18dB, I almost use pure RNN such as bidirectional rnn or attention rnn,this is different with you,do you have your acc in 18dB ?

**Comment by Ostnie** [comment]
I just use your CNN model and get acc 56%，but if I change input shape [128,2] instead [2,128] the acc will reach 76%,both lower than lstm

lstm+cnn model get 75% when input size is [2.128]

**Comment by LionAE** [comment]
Hi, I just saw the issue.  I updated weeks ago, the results in an other repository. You can see the confusion matrix.
The shape of input is (2, 128) since it's I/Q samples representations, so the 2 columns, one is for real and the other for complex values of signal. You can reshape your data.
The thing about LSTM, is that since the nature of signals are very complex to learn, having layers that enable information to persist for a long time is important, also training on CNN using NVIDIA 1080 Ti, I reached more than 80% accuracy. This is why you have a combination of CNN and LSTM, where LSTM are built on top of CNN layers.
Yeap, the original dataset, contains signals with different modulations for range of SNRs (-20 db to +18 db), the confusion matrix gives you an insight about how the samples were classified comparing to their original truth labels.
